Repository okezieobi/mono-webapp, pull requests merged in 2020-08, with the labels that each got.

#5 Fix 1
  README.md
  app/.eslintrc.js
  app/.gitignore
  app/README.md
  app/package-lock.json
  app/package.json
  app/public/favicon.ico
  app/public/index.html
  app/public/logo192.png
  app/public/logo512.png
  app/public/manifest.json
  app/public/robots.txt
  app/src/App.jsx
  app/src/App.test.js
  app/src/Components/Home.jsx
  app/src/Mono.js
  app/src/index.css
  app/src/index.jsx
  app/src/logo.svg
  app/src/serviceWorker.js
  app/src/setupTests.js
  app/src/svg/Home.svg
  app/src/svg/Home.svg:Zone.Identifier
  package.json
Labels: enhancement

#7 Fix deployment on Heroku
  app/package-lock.json
  app/package.json
Labels: bug

#8 Okezieobi/issue2
  app/src/App.jsx
  app/src/Components/Dashboard.jsx
  app/src/Components/Home.jsx
  app/src/Mono.js
  app/src/services/Fetch.js
Labels: enhancement

#10 Add a Codacy badge to README.md
  README.md
Labels: documentation
